name: Pipeline

on: 
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Actions
      uses: actions/checkout@v3
      with:
        repository: jonaser06/scripts-cicd
        ref: main
        token: ${{secrets.GH_TOKEN}}
        path: .action/
    
    - name: Execute Function
      uses: ./.action/workflows/function
      with:
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}