name: Pipeline

on: 
  push:
    branches:
      - main

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Actions
      uses: actions/checkout@v3
      with:
        repository: jonaser06/scripts-cicd
        ref: main
        token: ${{secrets.GH_TOKEN}}
        path: .action/
    
    - name: Execute Function
      uses: ./.action/workflows/function
      with:
        AWS_DEFAULT_REGION: 'us-east-1'